baseURL: https://mybeer.recipes
languageCode: en-us
title: mybeer.recipes
publishDir: docs
params:
    favicon: img/favicon.ico
    social:
    - title: twitter
      url: http://twitter.com/MybeerRecipes
    - title: github
      url: https://github.com/mybeer-recipes
    - title: gitter
      url: https://gitter.im/mybeer-recipes/community