name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Hugo Build
      uses: klakegg/actions-hugo@1.0.0
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'      
